# This file was generated by GoReleaser. DO NOT EDIT.
cask "ele" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "af3ef5f713ca042872ce47c7309ab5bb5e3310743a857e066388aa9c835135f4"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "09160d958c4934df09bc058e8ad5c535f4d8d6ef5724f43f913dcddb514846f7"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62a4a05b7f3c1412628f2385211469293adf56e3f99a8d5fe71741a2c1c90388"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "380c5e12699943bddc38d0d39c06a1763fa819b141f3ac576c515ee3e28146df"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ele"
  desc "Quiet the elephant — a drop-in pg_restore wrapper with live progress and a classified error summary"
  homepage "https://github.com/amberpixels/ele"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ele"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ele"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ele wraps pg_restore, which is NOT installed by this cask.
    Make sure pg_restore is on your PATH — for example:
      brew install libpq && brew link --force libpq
    or install the full server with:
      brew install postgresql@17
  EOS
end
