# This file was generated by GoReleaser. DO NOT EDIT.
cask "ele" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "5a2ca0c1a6304c6f29d1328cbbf91737484ce245eb2f220783345285f2730446"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d6533381d9e7bbdf8ea14805ad546996c85e85a90b6c219b9c8f6f1661dfcc7"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b75d3e56492d520081165288ba799340c00abca6eb7f5fc66b77e82cd985b040"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b13f6e11f17ecca9e9ac736c1ca7e9c4433dc0ef9223012d6620f7585ea07022"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ele"
  desc "Quiet the elephant — a drop-in pg_restore wrapper with live progress and a classified error summary"
  homepage "https://github.com/amberpixels/ele"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ele"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ele"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ele wraps pg_restore, which is NOT installed by this cask.
    Make sure pg_restore is on your PATH — for example:
      brew install libpq && brew link --force libpq
    or install the full server with:
      brew install postgresql@17
  EOS
end
