# This file was generated by GoReleaser. DO NOT EDIT.
cask "ele" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ad41829161744bd9b3428c3e0dce68b8485622afe4e5d56de9f93bae90164146"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c7410e382e48159d12c51c5d7cb660e50c382a288c3a60fdfdd325464414fe32"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "719fcda8b13092f735a97c336b22dc2bd3df55edeb9289968a8c83d8ec83a1dc"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d95328a2436ce7afae0f62e46b67e520ce495affc0cd8507b22c093623327eb"
      url "https://github.com/amberpixels/ele/releases/download/v#{version}/ele_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ele"
  desc "Quiet the elephant — a drop-in pg_restore wrapper with live progress and a classified error summary"
  homepage "https://github.com/amberpixels/ele"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ele"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ele"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ele wraps pg_restore, which is NOT installed by this cask.
    Make sure pg_restore is on your PATH — for example:
      brew install libpq && brew link --force libpq
    or install the full server with:
      brew install postgresql@17
  EOS
end
